expected_results = {
    'Bassdrum-01.wav': 'membrane',
    'Bassdrum-02.wav': 'membrane',
    'Bassdrum-03.wav': 'membrane',
    'Bassdrum-04.wav': 'membrane',
    'Bassdrum-05.wav': 'membrane',
    'Bdrum13.wav': 'membrane',
    'Bdrum14.wav': 'membrane',
    'Bdrum15.wav': 'membrane',
    'Bdrum1.wav': 'membrane',
    'Bdrum6.wav': 'membrane',
    'Hat Closed-02.wav': 'plate',
    'Hat Open-01.wav': 'plate',
    'Hat Open-02.wav': 'plate',
    'Hat Open-03.wav': 'plate',
    'Hat Open-04.wav': 'plate',
    'Hat Pedal-01.wav': 'plate',
    'Hat Pedal-02.wav': 'plate',
    'Knock-01.wav': 'membrane',
    'Knock-02.wav': 'membrane',
    'Ride-01.wav': 'plate',
    'Ride-02.wav': 'plate',
    'Ride-03.wav': 'plate',
    'Rimshot1.wav': 'membrane',
    'Rimshot2.wav': 'membrane',
    'Snare10.wav': 'membrane',
    'Snare11.wav': 'membrane',
    'Snare12.wav': 'membrane',
    'Snare13.wav': 'membrane',
    'Snare14.wav': 'membrane',
    'Snare15.wav': 'membrane',
    'Snare16.wav': 'membrane',
    'Snare17.wav': 'membrane',
    'Snare18.wav': 'membrane',
    'Snare19.wav': 'membrane',
    'Snare20.wav': 'membrane',
    'Snare21.wav': 'membrane',
    'Snare1.wav': 'membrane',
    'Snare2.wav': 'membrane',
    'Snare3.wav': 'membrane',
    'Snare4.wav': 'membrane',
    'Snare5.wav': 'membrane',
    'Snare6.wav': 'membrane',
    'Snare7.wav': 'membrane',
    'Snare8.wav': 'membrane',
    'Snare9.wav': 'membrane',
    'Stick.wav': 'membrane',
    'Tamb.wav': 'membrane',
    'Timb1.wav': 'membrane',
    'Timb2.wav': 'membrane',
    'Tom-04.wav': 'membrane',
    'Tom H-01.wav': 'membrane',
    'Tom H-02.wav': 'membrane',
    'Tom H-03.wav': 'membrane',
    'Tom L-01.wav': 'membrane',
    'Toml L-02.wav': 'membrane',
    'Toml L-03.wav': 'membrane',
    'Tom M-03.wav': 'membrane',
}
